server:
  port: 8002
#mybatis:
#  mapperLocations: classpath:mybatis/mapper/*.xml
#  type-aliases-package: com.kuang.springcloud.pojo     #所有Entity别名类所在包
#  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: provider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    url: jdbc:mysql://localhost:3306/mydb1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.175:8010/eureka/
  instance:
    instance-id: provider8001
