server:
  port: 8001
  servlet:
    context-path: /portal
spring:
  profiles:
    active: dev
  #配置 Jpa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000
    lettuce:
      pool:
        #最大连接数
        max-active: 20
        max-wait: -1

config:
  loginTokenFilter:
    ignoredUrls:
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50