#配置数据源
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    # 德鲁伊数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.3.85:3306/adminniu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/adminniu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 初始连接数
  #initial-size: 5
    dbcp2:
      # 最小连接数
      min-idle: 15
      # 最大连接数
      #max-active: 30
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 180
      # 获取连接超时时间
      max-wait-millis: 3000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      #max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      #defaultZone: http://192.168.3.85:8010/eureka/
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: localhost
    hostname: portal #Eureka服务端的实例名字